project_example should only list hostnames
FlominatorTM/wikiblame pull request #35
Opened 2021-11-21 14:54 UTC by kkotenko

I discovered that the translations also translated the hostnames. This sets a bad example for users. This commit reverts that.

2022-05-22 09:28 UTC, FlominatorTM commented
Somehow I missed this one, sorry. The thing is, that we have to change this over at @translatewiki , else it will be overwritten the next time again.

2022-10-08 15:30 UTC, waldyrious commented
Weirdly, I don't see the `project_example` key in translatewiki's [list of messages for Wikiblame](https://translatewiki.net/w/i.php?title=Special:Translate&group=wikiblame), even though there does seem to be translations there: https://translatewiki.net/wiki/Special:Translations?message=Wikimedia%3AMessages%5Cx5b%27project_example%27%5Cx5d&namespace=1206

Any idea why that may be?

2022-11-22 04:56 UTC, FlominatorTM commented
> Weirdly, I don't see the `project_example` key in translatewiki's [list of messages for Wikiblame](https://translatewiki.net/w/i.php?title=Special:Translate&group=wikiblame), even though there does seem to be translations there: https://translatewiki.net/wiki/Special:Translations?message=Wikimedia%3AMessages%5Cx5b%27project_example%27%5Cx5d&namespace=1206
> 
> Any idea why that may be?

Not sure I got the question right, maybe @translatewiki can say something about it?

2025-01-26 11:34 UTC, Etilmetilketilvinil commented on wikiblame_inc/haw.php
> +$messages['project_example'] = 'wikipedia, wikisource, wikimedia, wikidata, …';
78

2025-06-05 08:56 UTC, pzhlkj6612 commented
Hi there! In d4c10ea9c5f64b44816ef3d4d4eda45533853d2a, my friend and I have corrected some translation about "project_example" and other strings. Please have a look.

2025-06-05 09:50 UTC, pzhlkj6612 commented
Hi, @FlominatorTM !

> Nice idea, but these come from Translatewiki.net and have to be changed there, else they will be overwritten by their next push.

Hmm, I meant that the auto updated (imported) translation from Translatewiki.net is a newer version made by my friend and me. To deploy the new translation, what we should do?

2025-06-05 10:10 UTC, FlominatorTM commented
wikipedia.ramselehof.de I deploy once per month, the one on labs might be older

2025-06-05 15:21 UTC, pzhlkj6612 commented
Okay! Let's wait for the next deployment and see if we are satisfied with the new translation.

2026-05-18 07:49 UTC, tomorrow5513 reviewed
[Archive.zip](https://github.com/user-attachments/files/27949487/Archive.zip)

2026-05-19 22:58 UTC, tomorrow5513 requested changes

2026-06-12 05:16 UTC, FlominatorTM commented
Again, @tomorrow5513, the changes have to be performed at [https://translatewiki.net/ Translatewiki], since they are part of the translation.

2026-06-16 06:02 UTC, pzhlkj6612 commented
I will take a look at the recently added `project_example` soon:

https://github.com/FlominatorTM/wikiblame/blob/a6514a8801196070350843e26fb8211f28da55b6/wikiblame_inc/ps.php#L31

2026-06-29 17:28 UTC, pzhlkj6612 commented
> I will take a look at the recently added `project_example` soon:
> 
> https://github.com/FlominatorTM/wikiblame/blob/a6514a8801196070350843e26fb8211f28da55b6/wikiblame_inc/ps.php#L31

Done, 40a5e43ee9b5fb7b335192573f18dd7b11975dd6. We've made it before July.

2026-07-01 16:58 UTC, FlominatorTM commented
Since we now all agree, that translatewiki is the way to go, I will close this PR.

2026-07-01 16:58 UTC, closed without merging